### ISSUE TITLE
Add 2.5x and 3x speed as well

### ISSUE THREAD

**Issue by RajParab** [avi12/youtube-speed-control#1]
Please add 2.5x and 3x speed as well and  republish the addOn that would be very useful for me Thanks

**Comment by avi12** [comment]
Sorry for the late response. I've only seen this issue now
I believe I could add 2.5x and 3x

**Comment by avi12** [comment]
Even better in [1.1.2](../releases/tag/1.1.2):
![2021-01-29_23-31-38](https://user-images.githubusercontent.com/6422804/106329456-23c42c80-628a-11eb-945b-eba2f13ac218.png)
