### ISSUE TITLE
customize button controls

### ISSUE THREAD

**Issue by myriapoleis** [avi12/youtube-speed-control#10]
### Is your feature request related to a problem? Please describe

instead of just having shift + > and shift + <, it could be customized to take specific input such as `s` and `d`. i only suggest this because a chrome extension exists with the same functionality.

### Is it a change to the extension's functionality or to the pop-up settings page?

Extension's functionality

**Comment by avi12** [comment]
Due to the low volume of users on [Chrome](https://chrome.google.com/webstore/detail/dmpbgbehgckaijcpmodinibhkdgbifif) (<img src="https://img.shields.io/chrome-web-store/users/dmpbgbehgckaijcpmodinibhkdgbifif?color=white&label=&style=flat-square" align="top" alt="users count">), I decided to stop maintaining it

**Comment by avi12** [comment]
[This one](https://chrome.google.com/webstore/detail/hdannnflhlmdablckfkjpleikpphncik) seems to be working well

**Comment by myriapoleis** [comment]
sorry, perhaps i gave you the wrong idea

i am referring to a lacking trait of the opera version of this extension, by comparing it to other chrome extensions i am aware of. 

opera does not have a variety of high quality options to achieve this end, unfortunately

what i'd like to see is the chrome extension's customizable keypress-based speed up or slow down, adopted into the opera extension.

**Comment by avi12** [comment]
You can run almost any Chrome extension on Opera though
![image](https://github.com/avi12/youtube-speed-control/assets/6422804/dce3e4a9-2673-4451-8d80-ca3121090ac5)

**Comment by myriapoleis** [comment]
i. may be a fool lmao

thanks for the help and sorry to bother, new to opera

**Comment by avi12** [comment]
No worries, happy to help :)
