### ISSUE TITLE
[Bug] Pressing on notifications resets speed

### ISSUE THREAD

**Issue by Primake** [avi12/youtube-speed-control#11]
### Describe the bug

If I have changed the speed manually for a specific video and click on notifications the speed goes back to the usual.
For example: I normally view videos at 2 speed, but music I manually slow down to 1 speed. If I then click on notifications, it goes back to the default I set of 2 speed.

### How to reproduce

While playing a video change speed manually (pressing '<' or '>'), then click on notifications and the speed will return to what it was before changing it manually.

I have only tried on Opera GX

### Expected behavior

It shouldn't change speed.

### What browser(s) can you reproduce the issue on?

Opera

### What OS does it occur on?

Windows

### What's the version you're running?

2.1.6

**Comment by avi12** [comment]
Considering the low number of users on Chrome (![users count](https://img.shields.io/chrome-web-store/users/dmpbgbehgckaijcpmodinibhkdgbifif?color=white&label=users&style=flat-square)), I decided to stop maintaining this extension and focus my efforts on other projects
