### ISSUE TITLE
 Support Firefox for mobile

### ISSUE THREAD

**Issue by dvorapa** [avi12/youtube-speed-control#3]

**Comment by avi12** [comment]
Is there really a point to support FIrefox on mobile, considering that the common way to watch YouTube is via its app?

**Comment by avi12** [comment]
I'm not saying "I will not support"; I'm just asking a question if it's worth the time to make such a modification

**Comment by dvorapa** [comment]
I understand. But YouTube app does not allow custom speed. It does allow only certain speeds, that are not usable when you are a musician or a dancer and need to slow things down to a certain rate (90 %, 95 %, 85 %). That's primarily why I (as a dancer) love your addon as it makes it as simple as possible. Also it is extremely easy to use as it is completely outside YouTube UI. So I don't have to complicatedly navigate through YouTube submenus to search for speed changer, I can open speed changer in one click/tap. So extensions like this are the only thing we can deal with these two YouTube limitations. People usually use Chrome as there is a good extension for Google Chrome mobile. I don't like Chrome and I also don't like that extension as it is a little bit harder to use than yours.

**Comment by avi12** [comment]
Makes sense
I will try my best to support the mobile Firefox as well

**Comment by avi12** [comment]
@dvorapa Unfortunately, Mozilla has started remaking Firefox for Android from the ground up, thus for the meantime, until they will let every developer publish his/her extension on Android, I cannot support Firefox for Android >68
For more information: https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android
