### ISSUE TITLE
Add keyboard shortcuts (new feature)

### ISSUE THREAD

**Issue by Jonatas4ndrade** [avi12/youtube-speed-control#5]
A simple speed up / speed down button would be a very nice and somewhat simple feature to add.

As most people use this extension for studying, they might need to change speed many times to match the content difficulty level. Having to do so with the mouse can become annoying over time.

I do suggest three shortcuts: ramp up, tone down, and reset (sets the speed to 1x).

To go the extra mile, make the interval customizable. Otherwise, 0.25 increments/decrements would be a good value.

**Comment by avi12** [comment]
Implementing this should be easy enough

>  reset (sets speed to 1x).

What shortcut do you think would be appropriate for a reset?
