### ISSUE TITLE
Keyboard shortcuts in non English layout

### ISSUE THREAD

**Issue by rylkou** [avi12/youtube-speed-control#8]
The shortcut 'Shift' + '>' can't increase the speed more than 2x when I switch the keyboard to Russian layout. In Russian layout 'Shift' + '<' and 'Shift' + '>' work by default, as without YouTube Speed Control addon, these shortcuts change speed from 0.25x to 2x only. Generally in Russian layout I can't print '<' or '>', these keys print Russian letters: Б, Ю. May be this can help to understand and fix.

**Comment by avi12** [comment]
When you go to [this website](https://keycode.info) and press `<`/`>`,  what is in `event.key`?

**Comment by rylkou** [comment]
In English keyboard layout:
event.key = < / >
event.which = 188 / 190
event.code = Comma / Period

In Russian keyboard layout:
event.key = Б / Ю
event.which = 188 / 190
event.code = Comma / Period

**Comment by avi12** [comment]
Ok, and you expect to press `Б` / `Ю` to change the video speed, rather than pressing `<` / `>`?
Lemme ask it differently: without the extension, do you typically change the video speed using `Б` / `Ю`?

**Comment by rylkou** [comment]
Yes.
< / > characters are not available on Russian layout. Generally to type them, I need to switch out of Russian layout. It's habitual action. But all or almost all default YouTube hot keys works in both layouts. I can change the video speed using Б / Ю without the extension. Even with your extension I can change speed using Б / Ю, but in this case probably default YouTube hot key works, because I can't add more than 2x in Russian layout.

**Comment by avi12** [comment]
I guess I need to check by the `event.code`, in addition to `event.key`

**Comment by rylkou** [comment]
Or event.code without event.key

**Comment by avi12** [comment]
Or that, but solely relying on `event.code` will ignore RTL languages that expect pressing the `<`/`>` keys to behave as expected, and I happen to have an RTL-supported keyboard, so I know

**Comment by avi12** [comment]
Also, I'm debating whether to support speeding up/down Shorts

**Comment by avi12** [comment]
@rylkou Please install it [manually](https://www.youtube.com/watch?v=aMxenpDBvN4) and let me know if that works
[youtube-speed-control-2.1.5.zip](https://github.com/avi12/youtube-speed-control/files/7866601/youtube-speed-control-2.1.5.zip)

**Comment by avi12** [comment]
I ended up installing a Russian keyboard to test it, and it works nicely

**Comment by rylkou** [comment]
That works in my Opera and Chrome, thank you.

**Comment by avi12** [comment]
I pushed update 2.1.5 to the stores (Chrome, Edge, Firefox, Opera)
It's already available on [Opera](https://addons.opera.com/en/extensions/details/youtube-speed-control), and it'll hopefully be available on Chrome in a day or so
Please install it from the respective extension store ASAP so you get automatic updates

**Comment by avi12** [comment]
Nevermind, you can use the Chrome Web Store version
I'm shocked that it took 12 minutes to approve it
![image](https://user-images.githubusercontent.com/6422804/149503152-f12159a5-9339-4f19-b169-18be6c0f5ac1.png)
